In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
df = pd.read_csv('/kaggle/input/datasets/terminus7/pokemon-challenge/pokemon.csv')
data2 = pd.read_csv('/kaggle/input/datasets/terminus7/pokemon-challenge/pokemon.csv')
data3 = pd.read_csv('/kaggle/input/datasets/terminus7/pokemon-challenge/pokemon.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        799 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [4]:
df.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

In [5]:
df.tail(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
797,798,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,799,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,800,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

# **ÖN İŞLEME**

**Veri Temizleme (Data Cleaning)**: Gürültülü, eksik, hatalı ve tutarsız veriler temizlenir/düzeltilir.

**Eksikliklerin Tamamlanması**: Pokémon veri setinde 'Type 2' alanındaki eksik (NaN) değerleri 'None' veya 'Yok' olarak tamamlıyoruz.

In [6]:
df['Type 2'] = df['Type 2'].fillna('None')
df.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False

**Tekrar Eden Kayıtların (Duplicate) Temizlenmesi**: Ders notlarına göre aynı kayıtlar tekrar ediyorsa tekilleştirilir.

In [7]:
df.drop_duplicates(subset=['#'], keep='first', inplace=True)
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,None,39,52,43,60,50,65,1,False

**Metinlerdeki Gürültü ve Gramer Düzenlemeleri**: Gereksiz karakterlerin temizlenmesi ve tek formata getirilmesi.

In [8]:
df['Name'] = df['Name'].str.strip()
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,4,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,5,Charmander,Fire,None,39,52,43,60,50,65,1,False

# **VERİ SEÇME**

> Büyük veri yığınları veya veri tabanları içerisinden, belirlenen amaca, hipoteze ya da çözülmek istenen probleme uygun olan veri grubunun (satır bazlı hedef verinin) seçilmesi, gereksiz veya ilgisiz kısımların atılmasıdır.

In [9]:
fire_pokemons = df[df['Type 1'] == 'Fire']
fire_pokemons.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,5,Charmander,Fire,None,39,52,43,60,50,65,1,False
5,6,Charmeleon,Fire,None,58,64,58,80,65,80,1,False
6,7,Charizard,Fire,Flying,78,84,78,109,85,100,1,False

# **VERİ DÖNÜŞTÜRME**

**Verileri Toplama**: İstatistiksel analiz veya benzer içerikleri gruplama amacı doğrultusunda bilgilerin toplanıp özetlendiği işlemlerdir. Tavsiye sistemlerinde ve hedef kitle çalışmalarında kullanılır.

In [10]:
df['Total_Power'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
df[['Name', 'Total_Power']].head(3)

        Name  Total_Power
0  Bulbasaur          318
1    Ivysaur          405
2   Venusaur          525

**Yeni Nitelik Oluşturma (Attribute Construction)**: Var olan nitelikleri daha iyi temsil edecek nitelikler oluşturma işlemidir.

In [11]:
df['Attack_Defense_Ratio'] = df['Attack'] / (df['Defense'] + 1) # Sıfıra bölünme hatasını önlemek için +1
df[['Name', 'Attack_Defense_Ratio']].head(3)

        Name  Attack_Defense_Ratio
0  Bulbasaur               0.98000
1    Ivysaur               0.96875
2   Venusaur               0.97619

**Kesimlere Ayırma (Data Discretization)**: Sürekli verilerin (Yaş, Hız vb.) belirli aralıklı etiketlerle kategorik verilere dönüştürülmesi.

In [12]:
bins = [0, 50, 90, 200]
labels = ['Low Speed', 'Medium Speed', 'Very Fast']
df['Speed_Category'] = pd.cut(df['Speed'], bins=bins, labels=labels)

df[['Name', 'Speed', 'Speed_Category']].head(3)

        Name  Speed Speed_Category
0  Bulbasaur     45      Low Speed
1    Ivysaur     60   Medium Speed
2   Venusaur     80   Medium Speed

**Veri Normalleştirme**: Farklı kaynaklardan gelen farklı büyüklükteki değerlerin aynı aralıkta temsil edilmesini sağlar

In [13]:
numeric_cols = ['HP', 'Attack', 'Defense', 'Speed']

**Min-Max Scaler**: Sayısal verileri belirli bir aralığa, genellikle [0, 1] aralığına doğrusal olarak dönüştürmek için kullanılan temel bir ön işleme tekniğidir.

In [14]:
minmax_scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[numeric_cols] = minmax_scaler.fit_transform(df[numeric_cols])
df_minmax[numeric_cols].head(3)

         HP    Attack   Defense     Speed
0  0.173228  0.237838  0.195556  0.228571
1  0.232283  0.308108  0.257778  0.314286
2  0.311024  0.416216  0.346667  0.428571

**Z-Score**: Bir veri noktasının veri kümesinin ortalamasından kaç standart sapma uzaklıkta olduğunu gösteren istatistiksel bir ölçüdür.

In [15]:
z_scaler = StandardScaler()
df_zscore = df.copy()
df_zscore[numeric_cols] = z_scaler.fit_transform(df[numeric_cols])
df_zscore[numeric_cols].head()

         HP    Attack   Defense     Speed
0 -0.950626 -0.924906 -0.797154 -0.801503
1 -0.362822 -0.524130 -0.347917 -0.285015
2  0.420917  0.092448  0.293849  0.403635
3  0.420917  0.647369  1.577381  0.403635
4 -1.185748 -0.832419 -0.989683 -0.112853

# **VERİ İNDİRGEME**

**Sayıca Azaltma (Row Reduction)**: m azaltma da denir. Çok fazla kayıt varsa temsilci alt küme (örneklem) seçilir.

In [16]:
print("dataframe satır sayısı: " ,len(df))
sampled_pokemon_df = df.sample(n=400,random_state=1)
print("örneklem satır sayısı: " ,len(sampled_pokemon_df))

dataframe satır sayısı:  800
örneklem satır sayısı:  400

In [17]:
sampled_pokemon_df.head(3)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total_Power,Attack_Defense_Ratio,Speed_Category
8,9,Mega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634,1.316456,Very Fast
510,511,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False,494,1.210526,Medium Speed
175,176,Sentret,Normal,None,35,46,34,35,45,20,2,False,215,1.314286,Low Speed

**Öznitelik Seçimi (Feature Selection)**: n azaltma da denir. Analize gereksiz sütunlar dahil edilmeyerek boyut indirgenir ve performans artırılır. Sadece model için kritik olan sayısal özellikleri tutuyoruz.

In [18]:
reduced_columns = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']
reduced_pokemon_df = df[reduced_columns]
reduced_pokemon_df.head(3)
#Bunu biz manuel seçtik "güç özellikleri"ne göre

   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed
0  45      49       49       65       65     45
1  60      62       63       80       80     60
2  80      82       83      100      100     80

> **Korelasyon**: Verilerin birbiriyle olan ilişkisi. Bilgi Keşfi (KDD) süreçlerinde korelasyon, iki veya daha fazla değişken (sütun/özellik) arasındaki doğrusal ilişkinin yönünü ve gücünü gösteren istatistiksel bir ölçüdür.
> Öznitelik seçiminde korelasyon olabildiğince düşük (0'a yakın) tutulur.

In [19]:
numeric_cols = ['HP', 'Attack', 'Sp. Atk', 'Defense', 'Sp. Def', 'Speed', 'Total_Power', 'Attack_Defense_Ratio', 'Legendary']

# Filtre Yöntemi: Pearson Korelasyon Matrisi Hesaplama
corr_matriks = df[numeric_cols].corr(numeric_only=True)
corr_matriks.corr()

,HP,Attack,Sp. Atk,Defense,Sp. Def,Speed,Total_Power,Attack_Defense_Ratio,Legendary
HP,1.000000,0.165296,0.211392,0.248677,0.343560,-0.202192,0.505419,-0.270131,0.005305
Attack,0.165296,1.000000,-0.012716,0.153542,-0.199709,0.076461,0.313648,0.372294,-0.135599
Sp. Atk,0.211392,-0.012716,1.000000,0.134058,0.508446,0.414910,0.681213,-0.239630,0.367404
Defense,0.248677,0.153542,0.134058,1.000000,0.711529,-0.369526,0.686808,-0.837236,0.135999
Sp. Def,0.343560,-0.199709,0.508446,0.711529,1.000000,-0.086297,0.781659,-0.828996,0.268217
Speed,-0.202192,0.076461,0.414910,-0.369526,-0.086297,1.000000,0.191059,0.282640,0.106254
Total_Power,0.505419,0.313648,0.681213,0.686808,0.781659,0.191059,1.000000,-0.582506,0.249213
Attack_Defense_Ratio,-0.270131,0.372294,-0.239630,-0.837236,-0.828996,0.282640,-0.582506,1.000000,-0.253715
Legendary,0.005305,-0.135599,0.367404,0.135999,0.268217,0.106254,0.249213,-0.253715,1.000000

**Filtreler Yöntemi (Filters)**: Korelasyon katsayısına (Pearson Matrix) bakılarak öznitelik seçilmesi mantığına dayanır. Tüm modeli çalıştırmadığı için süreç olarak hızlıdır. Ancak tekrarlayan özelliklerin seçilmesine yol açabilir.

In [20]:
df_numeric = df[numeric_cols]

X = df_numeric.drop(columns=['Legendary','Total_Power','Attack_Defense_Ratio']) # Bağımsız değişkenler
corr_matrix = X.corr().abs() #Pearson kolerasyon matrisi (mutlak değer-absolute)

# Simetrik tekrarları ve köşegendeki 1.0 değerlerini engellemek için Üst Üçgen Matrisini Alınır
upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

upper_tri

         HP    Attack   Sp. Atk   Defense   Sp. Def     Speed
HP      NaN  0.422386  0.362380  0.239622  0.378718  0.175952
Attack  NaN       NaN  0.396362  0.438687  0.263990  0.381240
Sp. Atk NaN       NaN       NaN  0.223549  0.506121  0.473018
Defense NaN       NaN       NaN       NaN  0.510747  0.015227
Sp. Def NaN       NaN       NaN       NaN       NaN  0.259133
Speed   NaN       NaN       NaN       NaN       NaN       NaN

In [21]:
# Belirlenen Eşik Değerinden (Threshold) Yüksek Olan Sütunları Bul
threshold = 0.5
to_drop = []

# Üst üçgen matrisindeki her bir sütun adını tek tek geziyoruz
for column in upper_tri.columns:
    # Sütundaki değerlerden herhangi biri belirlenen eşik değerinden (0.85) büyük mü?
    if (upper_tri[column] > threshold).any():
        # Eğer büyük bir değer varsa, bu sütun adını silinecekler listesine ekliyoruz
        to_drop.append(column)

In [22]:
X_filtered = X.drop(columns=to_drop)
X_filtered = X_filtered.corr().abs()
X_filtered = X_filtered.where(np.triu(np.ones(X_filtered.shape), k=1).astype(bool))

X_filtered

         HP    Attack   Sp. Atk   Defense     Speed
HP      NaN  0.422386  0.362380  0.239622  0.175952
Attack  NaN       NaN  0.396362  0.438687  0.381240
Sp. Atk NaN       NaN       NaN  0.223549  0.473018
Defense NaN       NaN       NaN       NaN  0.015227
Speed   NaN       NaN       NaN       NaN       NaN

**Paketleyiciler Yöntemi (Wrappers)**: Özelliklerin tek tek denenerek (ekleme, çıkarma veya özyinelemeli / Recursive) model üzerindeki etkisinin görüldüğü ve en iyi performans veren alt kümenin seçildiği yöntemdir. Süreç çok uzun sürer.

In [23]:
from sklearn.feature_selection import RFE # Recursive Feature Elimination
from sklearn.linear_model import LogisticRegression

# Bağımsız değişkenler (Öznitelikler) ve Hedef Değişken (Legendary: True/False)
X = df[['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']]
y = df['Legendary']

model = LogisticRegression(max_iter=1000)
rfe = RFE(estimator=model, n_features_to_select=3) # En iyi 3 özelliği seç
rfe.fit(X, y)

for i, col in enumerate(X.columns):
    print(f"{col}: Seçildi mi? -> {rfe.support_[i]} (Sıralama: {rfe.ranking_[i]})")

HP: Seçildi mi? -> False (Sıralama: 2)
Attack: Seçildi mi? -> False (Sıralama: 4)
Defense: Seçildi mi? -> True (Sıralama: 1)
Sp. Atk: Seçildi mi? -> True (Sıralama: 1)
Sp. Def: Seçildi mi? -> False (Sıralama: 3)
Speed: Seçildi mi? -> True (Sıralama: 1)

In [24]:
from sklearn.ensemble import RandomForestClassifier

# Gömülü Yöntem: Random Forest kullanarak öznitelik önem skorlarını model içinde çıkarma
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X, y)

importances = pd.Series(rf_model.feature_importances_, index=X.columns)

importances.sort_values(ascending=False)

Sp. Atk    0.234817
Speed      0.189176
HP         0.165952
Sp. Def    0.156722
Attack     0.141316
Defense    0.112017
dtype: float64